# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.5-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install git
      - run: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - run: sudo apt-get install -y nodejs
      - run: node -v
      - run: npm -v
      - run: npm install puppeteer
      - run: node puppeteer/exam.js
      - run: git status
      - run: git add --all
      - run: git commit -m "puppeteer test"
      - run: git push
      - run: git config --global user.email "son4ln@gmail.com"
      - run: git config --global user.name "Son Dang"

      # - run: php artisan serve