
version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
      # - image: circleci/postgres:9.6-alpine
      #   environment:
      #     POSTGRES_USER: postgres
      #     POSTGRES_DB: crluo_4

    working_directory: ~/laravel
    steps:
      - checkout
      # - run: sudo apt install -y libsqlite3-dev zlib1g-dev libpng-dev
      # - run: sudo docker-php-ext-install zip
      # - run: sudo docker-php-ext-install bcmath
      # - run: sudo docker-php-ext-install gd
      # - run: sudo apt install postgresql-client
      # - run: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
      # - run: sudo composer self-update
      # - restore_cache:
      #     keys:
      #       - composer-v1-{{ checksum "composer.lock" }}
      #       - composer-v1-
      # - save_cache:
      #     key: composer-v1-{{ checksum "composer.lock" }}
      #     paths:
      #       - vendor
      # - restore_cache:
      #     keys:
      #       - node-v1-{{ checksum "package.json" }}
      #       - node-v1-
      # - run: composer install --no-scripts
      # - run: sudo curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      # - run: sudo apt-get install -y nodejs
      # - run: node -v
      # - run: npm -v
      # - run: npm install puppeteer
      # - run: node puppeteer/exam.js
      # - run: mkdir -p /tmp/test-results
      # - store_test_results:
      #     path: /puppeteer/img
      # - store_artifacts:
      #     path: /puppeteer/img
      #     destination: test-results

      - run: ls -R
      - run: cd ./puppeteer/img
      - run: pwd